### ISSUE TITLE
mybinder from zenodo and some notebook issues

### ISSUE THREAD

**Issue by vuillaut** [cosimoNigro/agnpy#75]
Hi

First point is not an issue.
I just wanted to mention that I tried to run the published version of agnpy (on zenodo) in mybinder and that it worked fine. I thought you might be interested :)
https://mybinder.org/v2/zenodo/10.5281/zenodo.4311271

A couple of things that did not work:
- `sys.path.append("/home/jsitarek/zdalne/agnpy/agnpy/")` in `notebooks/experiments/basic/SSDisk.ipynb` - you probably don't want to keep this path 
- `from agnpy.synchrotron import R, epsilon_equivalency`  in `notebooks/experiments/basic/trapz_loglog_test.ipynb` does not work
- `../../data/sampled_taus/tau_dt_figure_14_finke_2016.txt` in `notebooks/experiments/basic/check_tau_dt.ipynb` should be replaced by `../../agnpy/data/[...]`
- some issues with `Quantities` in `Synchrotron.evaluate_sed_flux([....]` in `notebooks/experiments/basic/synchro_fit_trial.ipynb`

Cheers,

**Comment by cosimoNigro** [comment]
Thanks a lot @vuillaut.
The only notebooks that should be accessible to users are those in `docs/tutorials`.
Everything in `experiments` is modified and circulated between developers for testing and discussing.
Shall I remove this material completely from the repo?

By the way, checking the notebooks in the binder I forgot to make a new release with the newest documentation.
I will do it next week.

The issue you reported with `Quantities` was also reported by @jsitarek in #74. I will check it.

Thank you!

**Comment by vuillaut** [comment]
> Thanks a lot @vuillaut.
> The only notebooks that should be accessible to users are those in `docs/tutorials`.
> Everything in `experiments` is modified and circulated between developers for testing and discussing.
> Shall I remove this material completely from the repo?

I would not pretend to tell you how to manage your project :)
As a user, it might be interesting to have a warning in these notebooks that they are for developpers.

> By the way, checking the notebooks in the binder I forgot to make a new release with the newest documentation (and newest notebooks). I will do it next week.
> 
> The issue you reported with `Quantities` was also reported by @jsitarek in #74. I will check it.
> 
> Thank you!

No problem

**Comment by cosimoNigro** [comment]
Hi @vuillaut,

I re-organised the material in the sub-directories and the installation dependencies to be sure all the notebooks can be run on binder. 
In the main page there is now [a link to launch the repo on binder](https://github.com/cosimoNigro/agnpy#agnpy-binder).
The only tutorial not working is the external Compton one since it requires more memory than the one provided by Binder (2 GB - it's does a very large multidimensional integral). I'll try to fix this.

For the rest, I added a README.md in `experiments` specifying that is a sub-directory for developers only, and we discovered, thanks to @CerenOzen that the unit issue you reported is triggered by an old `astropy` version. 
I specified in the `setup.py` to use a newer one.

So I thinks all the problems you reported have been fixed :) and I can close this.
Thanks for reporting them!
